name: mall_chat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.6
  http: ^1.0.0
  intl: ^0.18.1
  provider: ^6.0.5
  qr_flutter: ^4.1.0
  shared_preferences: ^2.1.2
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/avatars/
    - assets/1.png
  fonts:
    - family: SFMono
      fonts:
        - asset: assets/fonts/SFMonoBold.OTF
        - asset: assets/fonts/SFMonoBoldItalic.OTF
        - asset: assets/fonts/SFMonoHeavy.OTF
        - asset: assets/fonts/SFMonoHeavyItalic.OTF
        - asset: assets/fonts/SFMonoLight.OTF
        - asset: assets/fonts/SFMonoLightItalic.OTF
        - asset: assets/fonts/SFMonoMedium.OTF
        - asset: assets/fonts/SFMonoMediumItalic.OTF
        - asset: assets/fonts/SFMonoRegular.OTF
        - asset: assets/fonts/SFMonoRegularItalic.OTF
        - asset: assets/fonts/SFMonoSemibold.OTF
        - asset: assets/fonts/SFMonoSemiboldItalic.OTF
